# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19b0cd62b5688f3d133ddad75d62b58c"
name = "uchatbot-plugin"
handle = "uchatbot-plugin"
application_url = "https://isolated-tracy-optional-excitement.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://isolated-tracy-optional-excitement.trycloudflare.com/auth/callback",
  "https://isolated-tracy-optional-excitement.trycloudflare.com/auth/shopify/callback",
  "https://isolated-tracy-optional-excitement.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
