# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7baf4e7946b81bcfcd9a98c80ac4d605"
name = "uchatbot-pluggin"
handle = "uchatbot-pluggin"
application_url = "https://energy-abu-dealing-cleanup.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://energy-abu-dealing-cleanup.trycloudflare.com/auth/callback",
  "https://energy-abu-dealing-cleanup.trycloudflare.com/auth/shopify/callback",
  "https://energy-abu-dealing-cleanup.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
