# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

<<<<<<< HEAD
client_id = "7baf4e7946b81bcfcd9a98c80ac4d605"
name = "uchatbot-pluggin"
handle = "uchatbot-pluggin"
application_url = "https://energy-abu-dealing-cleanup.trycloudflare.com"
=======
client_id = "8d0a28343fb384a159847610d6656557"
name = "uchatbot"
handle = "uchatbot"
application_url = "https://checklist-file-meal-pixel.trycloudflare.com"
>>>>>>> bc38db9ce04bd219a70dc27b0d1f1f35f8143699
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags"

[auth]
redirect_urls = [
<<<<<<< HEAD
  "https://energy-abu-dealing-cleanup.trycloudflare.com/auth/callback",
  "https://energy-abu-dealing-cleanup.trycloudflare.com/auth/shopify/callback",
  "https://energy-abu-dealing-cleanup.trycloudflare.com/api/auth/callback"
=======
  "https://checklist-file-meal-pixel.trycloudflare.com/auth/callback",
  "https://checklist-file-meal-pixel.trycloudflare.com/auth/shopify/callback",
  "https://checklist-file-meal-pixel.trycloudflare.com/api/auth/callback"
>>>>>>> bc38db9ce04bd219a70dc27b0d1f1f35f8143699
]

[pos]
embedded = false
